### ISSUE TITLE
Sorting Out Branches

### ISSUE THREAD

**Issue by davidamichelson** [srophe/manuscripts#36]
Please review the branches and prepare a list of which ones are newer than Master.

The real Master branch is names master- (maybe 2015 or Feb 27)

**Comment by davidamichelson** [comment]
I think this is the master: https://github.com/srophe/manuscripts/blob/Master-Feb-27-Merge-Copy

**Comment by PGAMiller** [comment]
Either this is the master we want to use:
https://github.com/srophe/manuscripts/blob/Master-Feb-27-Merge-Copy

Or this is:
https://github.com/srophe/manuscripts/blob/Justin-Editing-February

Justin's February file is farther ahead (136 commits to 80), but also has more commits behind the master (23 to 2).
